config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: %i[create update]
  get "/generate", to: "projects#new"
  get "/generate/:project_id/preview", to: "projects#preview", as: "preview"
  get "/dashboard", to: "dashboards#index"
  get "/generate/:project_id/jpg", to: "projects#jpg", as: "jpg"
  post "/generatepdf", to: "projects#generate"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :projects
end

app/models/design.rb
class Design < ApplicationRecord
  has_many :projects
end

app/models/font.rb
class Font < ApplicationRecord
  has_many :projects
end

app/models/layout.rb
class Layout < ApplicationRecord
  has_many :projects
end

app/models/placeholder.rb
class Placeholder < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :layout
  belongs_to :color
  belongs_to :design
  belongs_to :font
  belongs_to :user
  has_many :placeholders
  has_one_attached :logo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    #skip_before_action :authenticate_user!
    def index
      @projects = Project.where(user_id: current_user.id)
    end
    def preview
      @preview = Project.find(@project.id)
      builder = LayoutBuilder.new(@preview)
      @html = builder.build
      render :layout => false
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new update preview generate jpg]
  skip_before_action :verify_authenticity_token, only: %i[update generate jpg]

  def new
    if params[:project_id].present?
      @project = Project.find(params[:project_id])
    else
      if current_user.nil?
        @project = Project.create(layout_id: Layout.first.id, color_id: Color.first.id, design_id: Design.first.id, user_id: User.first.id, font_id: Font.first.id)
      else
        @project = Project.create(layout_id: Layout.first.id, color_id: Color.first.id, design_id: Design.first.id, user_id: current_user.id, font_id: Font.first.id)
      end
    end
    @fonts = FontList.list
    # raise
    logger.info "Processing the request..."
  end

  def update
    @project = Project.find(params["id"])
    #@project.update(logo: project_params[:logo])
    @project.update(layout_id: project_params[:layout_id])
    @project.update(design_id: project_params[:design_id])
    @project.update(color_id: project_params[:color_id])
    #raise
    font = Font.find_by(heading: font_params[:heading], paragraph: font_params[:paragraph])
    if font.nil?
      font = Font.create(heading: font_params[:heading], paragraph: font_params[:paragraph])
    end
    @project.update(font_id: font.id)

    redirect_to generate_path(project_id: @project.id)
  end

  def save
    if @project.save
      flash[:success] = "Layout is saved to your dashboard!"
      redirect_to dashboard_path
    else
      flash[:alert] = "Something went wrong. Please try again!"
      redirect_to new_path(@project)
    end
  end

  def preview
    @preview = Project.find(params[:project_id])
    builder = LayoutBuilder.new(@preview)
    @html = builder.build
    render :layout => false
  end

  def jpg
    @project = Project.find(params[:project_id])
    @kit = IMGKit.new('https://google.com')
    path = "app/assets/images/projects/project-#{params[:project_id]}.jpeg"
    file = @kit.to_file(path)
    send_data(file, type: "image/jpeg", filename: "project-#{params[:project_id]}.jpg")

    # redirect_to generate_path(project_id: @project.id)
  end

  # def generate
  #   @preview = Project.find(params[:project_id])
  #   builder = LayoutBuilder.new(@preview)
  #   @html = builder.build

  #   pdf = WickedPdf.new.pdf_from_string(@html)
  #   send_data pdf, :disposition => 'attachment', :filename=>"layout.pdf"
  # end

  private
  def project_params
    # :logo, was in params, now is commented out beacause logo upload button is ugly
    params.require(:project).permit(:layout_id, :design_id, :font_id, :color_id, :placeholder_id)
  end
  def font_params
    params.require(:font).permit(:heading, :paragraph)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#54aaaf">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#c7f8f8">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/dashboards/index.html.erb
<div class="container justify-content-between d-flex flex-column">
  <div class="row justify-content-center">
    <div id="dashboard" class="col col-md-10">
      <div class="header">
        <h1 class="text-center mb-2">Dashboard</h1>
      </div>
      <!-- Nav tabs -->
      <div class="d-flex justify-content-center">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-dash">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">My Saved Layouts</a>
          </li>
          <li class="nav-dash">
            <%= link_to "Create your new project!", generate_path, class: "nav-link active" %>
          </li>
        </ul>
      </div>
      <% unless @projects.empty? %>
        <div class="mx-auto mt-5 row iframe-container justify-content-center">
          <% @projects.each do |p| %>
            <div class="card col-xs-12 col-md-6 col-lg-4">
              <iframe scrolling="no" class="card-iframe-thumbnail" src="<%= preview_path(p) %>" frameborder="0"></iframe>
            </div>
          </div>
          <% end %>
        <% else %>
        <div class="mx-auto mt-5 row iframe-container justify-content-center">
          <h3 class="text-center">No saved projects</h3>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col col-md-10">
      <%= link_to "< Back", generate_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= meta_title %> | NoCoMo;</title>
  <meta name="description" content="<%= meta_description %>">
  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />
  <%= render 'application/favicon' %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  <%#= wicked_pdf_stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

</head>
<body class="<%= controller_name %> <%= action_name %>">
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>

  <%= javascript_pack_tag 'application' %>
  <%= render "shared/footer" %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</body>
</html>

app/views/pages/home.html.erb
<% content_for :meta_title, "Your 3-minute mockup builder" %>
<% content_for :meta_description, "Build your website mockup in less than 5 minutes!" %>
<% content_for :meta_image, "banner.svg" %>
<div class="home-banner">
  <div class="home-banner-content-wrapper">
    <div class="left">
      <h2 class="mb-3 h1">A beautiful landing page mockup in less than 5 minutes.</h2>
      <p class="big">No need for code or design.</p>
      <%= link_to "Get started", generate_path, class: "btn btn-big mt-3", id: "scroll-down" %>
    </div>
    <div class="right">
      <%= image_tag "banner.svg", alt: "Banner photo" %>
    </div>
  </div>
</div>
<div class="main">
  <div class="card-section">
    <h1 class="main-heading">Why use NoCoMo?</h1>
    <div class="home-card-wrapper">
      <div class="home-card">
        <%= image_tag "why-clean.svg", alt: "Quick but clean" %>
        <div class="home-card-product-infos">
          <h3>Quick but clean</h3>
          <p>Build a beautiful mockup without any experience!</p>
        </div>
      </div>
      <div class="home-card">
        <%= image_tag "why-time.svg", alt: "Don’t waste time"%>
        <div class="home-card-product-infos">
          <h3>Don’t waste time</h3>
          <p>Only a few clicks. Your mockup is done in no time!</p>
        </div>
      </div>
      <div class="home-card">
        <%= image_tag "why-build.svg", alt: "Build on it" %>
        <div class="home-card-product-infos">
          <h3>Build on it</h3>
          <p>Export it as code. Reuse it for the real website!</p>
        </div>
      </div>
    </div>
    <div class="button-wrapper">
      <%= link_to "Start now!", generate_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<div id="how-to" class="work-section">
  <h1>How does it work? </h1>
  <div class="work-content">
    <div class="row mb-5 mx-auto">
      <div class="work-card col-xs-12 col-md-8">
        <%= image_tag "4.svg", alt: "Choose design" %>
      </div>
      <div class="work-card col-xs-12 col-md-4">
        <h2>1. Choose your template</h2>
        <p>Do you want to show a shop, a business website or a blog? These kinds of websites are structured differently. Choose a template fitting your needs!</p>
      </div>
    </div>
    <div class="row my-5 mx-auto">
      <div class="work-card col-xs-12 col-md-4">
        <h2>2. Individualise your page</h2>
        <p>You want a rather minimalistic website with natural colours? No worries, we got you ;)</p>
      </div>
      <div class="work-card col-xs-12 col-md-8">
        <%= image_tag "5.svg", alt: "Individualise" %>
      </div>
    </div>
    <div class="row mt-5 mx-auto">
      <div class="work-card col-xs-12 col-md-8">
        <%= image_tag "6.svg", alt: "Export"%>
      </div>
      <div class="work-card col-xs-12 col-md-4">
        <h2>3. Download it!</h2>
        <p>Export the mockup as HTML or JPG and just insert it into your presentation. Voilà!</p>
      </div>
    </div>
  </div>
  <div class="button-wrapper">
    <%= link_to "Start now!", generate_path, class: "btn btn-primary" %>
  </div>
</div>
<hr>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <h1>What could it look like?</h1>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "preview-1.jpg", alt: "Photography layout, Minimal design", class: "d-block"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "preview-2.jpg", alt: "Business layout, Corporate design", class: "d-block"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "preview-3.jpg", alt: "Blog layout, Dark design", class: "d-block"%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="card-section">
  <h1 class="main-heading">Testimonials</h1>
  <div class="testimonial-card-wrapper">
    <div class="testimonial-card">
      <%= image_tag "testimonial-1.jpg", alt: "Happy customer 1" %>
      <div class="testimonial-card-product-infos">
        <h3>Friendly & efficient</h3>
        <p>Very user friendly & efficient for a small business owner</p>
        <cite>Riccardo O.</cite>
      </div>
    </div>
    <div class="testimonial-card">
      <%= image_tag "testimonial-2.jpg", alt: "Happy customer 2" %>
      <div class="testimonial-card-product-infos">
        <h3>Great tool</h3>
        <p>NoCoMo; gives you a lot of freedom in the design process.</p>
        <cite>Marc M.</cite>
      </div>
    </div>
    <div class="testimonial-card">
      <%= image_tag "testimonial-3.jpg", alt: "Happy customer 3" %>
      <div class="testimonial-card-product-infos">
        <h3>Fun factor</h3>
        <p>You can start playfully yet achieve impressive results quickly.</p>
        <cite>Victor N.</cite>
      </div>
    </div>
    <div class="testimonial-card">
      <%= image_tag "testimonial-4.jpg", alt: "Happy customer 4" %>
      <div class="testimonial-card-product-infos">
        <h3>Flexibility of design</h3>
        <p>The designs looks professional and allow for pixel-perfect customizations.</p>
        <cite>Sven H.</cite>
      </div>
    </div>
    <div class="testimonial-card">
      <%= image_tag "testimonial-5.jpg", alt: "Happy customer 5" %>
      <div class="testimonial-card-product-infos">
        <h3>Easy to use</h3>
        <p>The editor is very easy to understand.</p>
        <cite>Gabi B.</cite>
      </div>
    </div>
  </div>
</div>
</div>
<div class="work-section">
  <div class="work-content mb-5">
    <div class="work-card col-xs-12 col-md-8">
      <%= image_tag "7.svg", alt: "Photo build on it" %>
    </div>
    <div class="work-card col-xs-12 col-md-4">
      <h1>Start building your website now!</h1>
      <p>Without any prior knowledge you can create a perfect mockup. No matter what you are up to - a website, an online shop, a landing page or a blog - with NoCoMo; you can create it in no time!</p>
    </div>
  </div>
  <div class="button-wrapper">
    <%= link_to "Start now!", generate_path, class: "btn btn-primary" %>
  </div>
</div>
</div>

app/views/projects/color.html.erb
<style>
  <%= @color.css.html_safe %>
  .row {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
  }
  .color {
    height: 200px;
  }
  body {
    padding: 0;
    margin: 0;
    overflow: hidden;
  }
</style>
<body>
  <div class="row">
    <div class="color" style="background-color: var(--primary)"></div>
    <div class="color" style="background-color: var(--secondary)"></div>
    <div class="color" style="background-color: var(--secondary-light)"></div>
    <div class="color" style="background-color: var(--white)"></div>
    <div class="color" style="background-color: var(--dark)"></div>
  </div>
</body>

app/views/projects/new.html.erb
<% content_for :meta_title, "Generate your mockup" %>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-4 col-lg-4">
      <div>
        <h2>Create your new project!</h2>
        <form class="simple_form project-form col pl-0" id="edit_project_<%= @project.id %>" novalidate="novalidate" enctype="multipart/form-data" action="/projects/<%= @project.id %>" accept-charset="UTF-8" method="post">
          <input type="hidden" name="_method" value="patch">
        <!-- <div class="form-group file optional project_logo">
          <label class="file optional" for="project_logo">Logo</label>
          <input class="form-control-file file optional" type="file" name="project[logo]" id="project_logo">
        </div>
        <br> </br> -->
        <div class="form-group select optional project_layout_id">
          <label class="select optional" for="project_layout_id"> <strong> Layout </strong></label>
          <div class="btn-group btn-group-toggle button-group-green" data-toggle="buttons">
            <% Layout.all.each do |l| %>
            <label class="btn btn-outline-info m-2" for="layout-<%= l.id %>">
              <% unless @project.layout_id == l.id %>
              <input type="radio" id="layout-<%= l.id %>" name="project[layout_id]" value="<%= l.id %>" /> <%= l.name %>
              <% else %>
              <input type="radio" checked id="layout-<%= l.id %>" name="project[layout_id]" value="<%= l.id %>" /> <%= l.name %>
              <% end %>
            </label>
            <% end %>
          </div>
        </div>
        <div class="form-group select optional project_design_id">
          <label class="select optional" for="project_design_id"><strong>Design</strong></label>
          <div class="btn-group btn-group-toggle button-group-green" data-toggle="buttons">
            <% Design.all.each do |d| %>
            <label class="btn btn-outline-info m-2" for="design-<%= d.id %>">
              <% unless @project.design_id == d.id %>
              <input type="radio" id="design-<%= d.id %>" name="project[design_id]" value="<%= d.id %>" /> <%= d.name %>
              <% else %>
              <input type="radio" checked id="design-<%= d.id %>" name="project[design_id]" value="<%= d.id %>" /> <%= d.name %>
              <% end %>
            </label>
            <% end %>
          </div>
        </div>

        <div class="form-group select optional project_color_id">
         <label class="select optional" for="project_color_id"><strong>Color scheme</strong></label>
         <div class="btn-group btn-group-toggle button-group-green" data-toggle="buttons">
           <% Color.all.each do |c| %>
           <div class="label-wrap">
             <label class="btn btn-outline-info color-label" for="color-<%= c.id %>">
              <% cb = ColorBuilder.new(c) %>
              <div class="color-wrap">
                <%= cb.build.html_safe %>
              </div>
              <% unless @project.color.id == c.id %>
              <div>
                <input type="radio" id="color-<%= c.id %>" name="project[color_id]" value="<%= c.id %>" /><%= c.name %></div>
                <% else %>
                <div>
                  <input type="radio" checked id="color-<%= c.id %>" name="project[color_id]" value="<%= c.id %>" /><%= c.name %></div>
                  <% end %>
                </label>
              </div>
              <% end %>
            </div>
          </div>
          <br> </br>
          <div class="form-group select optional font_heading">
            <label class="select optional" for="font_heading"><strong>Headline font</strong></label>
            <select class="btn dropdown-toggle w-100 dropdown-borderless" name="font[heading]" id="font_heading">
              <% unless @project.font.nil? %>
              <option value="<%= @project.font.heading %>"><%= @project.font.heading %></option>
              <option value="Lato">------</option>
              <% end %>
              <%= @fonts.each do |f| %>
              <option value="<%= f[0] %>"><%= f[0] %></option>
              <% end %>
            </select>
            <br> </br>
          </div>
          <div class="form-group select optional font_paragraph form-group-valid">
            <label class="select optional" for="font_paragraph"><strong>Paragraph font</strong></label>
            <select class="btn dropdown-toggle w-100 dropdown-borderless" name="font[paragraph]" id="font_paragraph">
              <% unless @project.font.nil? %>
              <option value="<%= @project.font.paragraph %>"><%= @project.font.paragraph %></option>
              <option value="Lato">------</option>
              <% end %>
              <%= @fonts.each do |f| %>
              <option value="<%= f[0] %>"><%= f[0] %></option>
              <% end %>
            </select>
          </div>
          <div class="form-footer">
            <div>
              <input type="submit" name="commit" value="Update preview" data-disable-with="Update Project", class="btn btn-primary mr-1">
              <%= link_to 'Add to account', dashboard_path, class: 'btn btn-secondary ml-1' %>
            </div>
            <div>
              <%= link_to 'Export as JPG', "#", download: "nocomo-project-#{@project.id}.jpg", class: "btn btn-secondary" %>
              <%= link_to 'Export as Code', preview_path(@project), download: "nocomo-project-#{@project.id}.html", class: "btn btn-secondary" %>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="col-sm-12 col-md-8 col-lg-8 col-xl-7">
      <!-- <form action="/generatepdf" method="post" remote="true">
        <input id="generatepdf" type="submit" name="commit" value="Save as PDF" class="btn btn-outline-info " >
        <input hidden name="projectid" value="<%= @project.id  %>" class="btn btn-primary">
        <iframe name="iframe" id="preview" src="<%= preview_path(@project) %>" frameborder="0"></iframe>
      </form> -->
      <iframe name="iframe" id="preview" src="<%= preview_path(@project) %>" frameborder="0"></iframe>
    </div>
  </div>
</div>

<script>
  window.onload = () => {
    //iframe height
    const iframe = document.querySelector("iframe#preview");
    const height = iframe.contentDocument.documentElement.clientHeight;
    iframe.style.height = height + 2 + "px";
  }
</script>

app/views/projects/preview.html.erb
<% content_for :title, "Your website" %>
<%= @html.html_safe %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <ul>
    <li><a href="#" target="_blank"><i class="fa fa-facebook-f"></i></a></li>
    <li><a href="#" target="_blank"><i class="fa fa-instagram"></i></a></li>
    <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
    <li><a href="#" target="_blank"><i class="fa fa-vimeo-square"></i></a></li>
    <li><a href="#" target="_blank"><i class="fa fa-github"></i></a></li>
  </ul>
   <p>From NoCoMo with <i class="fas fa-heart" style="color:#e65c00"> </i></p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag("nocomo-logo.svg", class: "logo", alt: "NoCoMo; Logo") %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", "dashboard", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown account">
        <%= image_tag "1.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", dashboard_path, class: "dropdown-item"  %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>